### ISSUE TITLE
RecaptchaType class renamed, breaking a fresh install

### ISSUE THREAD

**Issue by alister** [JAIrwin/JAIContactBundle#1]
EWZRecaptchaBundle renamed the Type in v.1.4.2, [commit](https://github.com/excelwebzone/EWZRecaptchaBundle/commit/7a02b548912442fdc81d80c82e9a10ae91fb907c#diff-dd8c75e216eca966dcdccf85d544f4fcL13)

**Comment by JAIrwin** [comment]
The contact bundle was written after this version, so it's always used the newer Type class. I've updated the EWZRecaptchaBundle required version to ^1.4.2 to enforce this.

Thanks for the heads-up.
